// m_planet_state  -->     m_status m_situation  m_case  m_mode

// m_modes in missile
//const MISSILE_A_NO_SHOT = 'MISSILE_A_NO_SHOT';
const MISSILE_0_SHOT_FORWARD = 'MISSILE_0_SHOT_FORWARD';
const MISSILE_1_HITTING_PYLON = 'MISSILE_1_HITTING_PYLON';
const MISSILE_2_AFTER_PYLON_HIT = 'MISSILE_2_AFTER_PYLON_HIT';

const MISSILE_3_SECOND_PYLON_HIT = 'MISSILE_3_SECOND_PYLON_HIT';


const PYLON_0_NORMAL = 'PYLON_0_NORMAL';
const PYLON_1_HIT = 'PYLON_1_HIT';    // GREEN EDGES + BRIGHT
const PYLON_2_BRIGHT = 'PYLON_2_BRIGHT';
const PYLON_3_DIM = 'PYLON_3_DIM';



const ENEMY_0_FLOATING = 'enemy-float';
const ENEMY_1_BOUNCE = 'enemy-bounce';

// m_state in enemy
const ENEMY_1_HIT = 'ENEMY_1_HIT';     // green missile + green enemy
const ENEMY_2_LIFTING = 'ENEMY_2_LIFTING';

const ENEMY_3_ZOMBIE = 'ENEMY_3_ZOMBIE';




const LOOP_0_DESKTOP_START = 'LOOP_0_DESKTOP_START';
const LOOP_0_MOBILE_START = 'LOOP_0_MOBILE_START';

const LOOP_1_BEGIN = 'LOOP_1_BEGIN';
const LOOP_2_AFTER_BEGIN = 'LOOP_2_AFTER_BEGIN';
const LOOP_3_LANDING = 'LOOP_3_LANDING';
const LOOP_4_AFTER_LANDING = 'LOOP_4_AFTER_LANDING';
const LOOP_5_ELEVATOR = 'LOOP_5_ELEVATOR';
const LOOP_6_AFTER_ELEVATOR = 'LOOP_6_AFTER_ELEVATOR';

const LOOP_7_PLAY_NORMAL = 'LOOP_7_PLAY_NORMAL';

const LOOP_7_PLAY_HOLE_A_HIT = 'LOOP_7_PLAY_HOLE_A_HIT';
// const LOOP_7_PLAY_HOLE_B_INSIDE = 'LOOP_7_PLAY_HOLE_B_INSIDE';
// const LOOP_7_PLAY_HOLE_C_LEAVE = 'LOOP_7_PLAY_HOLE_C_LEAVE';

const LOOP_7_PLAY_A_JUMP_START = 'LOOP_7_PLAY_A_JUMP_START';
const LOOP_7_PLAY_B_JUMP_UP = 'LOOP_7_PLAY_B_JUMP_UP';
const LOOP_7_PLAY_C_JUMP_DOWN = 'LOOP_7_PLAY_C_JUMP_DOWN';

const LOOP_8_AFTER_PLAY = 'LOOP_8_AFTER_PLAY';
const LOOP_9_FLY = 'LOOP_9_FLY';

const LOOP_10_DEAD_START = 'LOOP_10_DEAD_START';

const LOOP_11_DEAD_FIELD = 'LOOP_11_DEAD_FIELD';
const LOOP_12_DEAD_SKY = 'LOOP_12_DEAD_SKY';

const LOOP_13_DONE = 'LOOP_13_DONE';





const LOOP_DEBUG_STOP = 'loop-none-debugging';





const SWIPE_UP = "swip-up";    // DBG_SWIP_UP

const SWIPE_DOWN = "swip-down";



const SWIPE_RIGHT = "swip-right";
const SWIPE_LEFT = "swip-left"; 