const MISSILE_0_NO_SHOT = "MISSILE_0_NO_SHOT";
const MISSILE_1_SHOT_FORWARD = "MISSILE_1_SHOT_FORWARD";
const MISSILE_2_HITTING_PYLON = "MISSILE_2_HITTING_PYLON";
const MISSILE_3_AFTER_PYLON_HIT = "MISSILE_3_AFTER_PYLON_HIT";
const MISSILE_4_SECOND_PYLON_HIT = "MISSILE_4_SECOND_PYLON_HIT";

const PYLON_0_NORMAL = "PYLON_0_NORMAL";
const PYLON_1_HIT = "PYLON_1_HIT";
const PYLON_2_BRIGHT = "PYLON_2_BRIGHT";
const PYLON_3_DIM = "PYLON_3_DIM";

const ENEMY_0_HUNTING = "ENEMY_0_HUNTING";
const ENEMY_1_BOUNCE = "ENEMY_1_BOUNCE";
const ENEMY_2_HIT = "ENEMY_2_HIT";
const ENEMY_3_LIFTING = "ENEMY_3_LIFTING";
const ENEMY_4_ZOMBIE = "ENEMY_4_ZOMBIE";

const LOOP_DEBUG_STOP = "loop-none-debugging";

const SWIPE_UP = "swip-up";
const SWIPE_DOWN = "swip-down";
const SWIPE_RIGHT = "swip-right";
const SWIPE_LEFT = "swip-left";
